#!/usr/bin/python
import re, sys

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

message_file = sys.argv[1]
f = open(message_file)
message = f.read()

regex_string = '^.+\#\d+.+$'
p = re.compile(regex_string)
if p.match(message) is None:
    print bcolors.FAIL + "======================" + bcolors.ENDC
    print bcolors.FAIL + "|Pivotal ID required  |" + bcolors.ENDC
    print bcolors.FAIL + "======================" + bcolors.ENDC
    print bcolors.FAIL + "This commit needs a pivotal story ID. e.g.: git commit -am'[#82695812] - message goes here .. ' where 82695812 is your pivotal ID" + bcolors.ENDC
    print "\n\n"
    sys.exit(1)
